"""initial persistence schema

Revision ID: 20260720_0001
Revises:
Create Date: 2026-07-20 12:11:50.034009
"""

from collections.abc import Sequence
from datetime import UTC, date, datetime
from uuid import UUID

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "20260720_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

CTRIP_PROVIDER_ID = UUID("00000000-0000-0000-0000-000000000001")


def _month_start(value: date) -> date:
    return date(value.year, value.month, 1)


def _shift_month(value: date, offset: int) -> date:
    month_index = value.year * 12 + value.month - 1 + offset
    year, zero_based_month = divmod(month_index, 12)
    return date(year, zero_based_month + 1, 1)


def _create_price_partitions() -> None:
    anchor = _month_start(datetime.now(UTC).date())
    for offset in range(-1, 3):
        start = _shift_month(anchor, offset)
        end = _shift_month(start, 1)
        name = f"price_observations_y{start.year:04d}m{start.month:02d}"
        start_iso = datetime(start.year, start.month, 1, tzinfo=UTC).isoformat()
        end_iso = datetime(end.year, end.month, 1, tzinfo=UTC).isoformat()
        op.execute(
            sa.text(
                f"CREATE TABLE IF NOT EXISTS {name} PARTITION OF price_observations "
                f"FOR VALUES FROM (TIMESTAMPTZ '{start_iso}') TO (TIMESTAMPTZ '{end_iso}')"
            )
        )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "providers",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("adapter_version", sa.String(length=80), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_providers")),
        sa.UniqueConstraint("code", name=op.f("uq_providers_code")),
    )
    op.bulk_insert(
        sa.table(
            "providers",
            sa.column("id", sa.Uuid()),
            sa.column("code", sa.String()),
            sa.column("display_name", sa.String()),
            sa.column("enabled", sa.Boolean()),
            sa.column("adapter_version", sa.String()),
        ),
        [
            {
                "id": CTRIP_PROVIDER_ID,
                "code": "ctrip",
                "display_name": "Ctrip",
                "enabled": True,
                "adapter_version": "initial",
            }
        ],
    )
    op.create_table(
        "search_queries",
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("query_hash", sa.String(length=64), nullable=False),
        sa.Column("trip_type", sa.String(length=16), nullable=False),
        sa.Column("adults", sa.SmallInteger(), nullable=False),
        sa.Column("children", sa.SmallInteger(), nullable=False),
        sa.Column("infants", sa.SmallInteger(), nullable=False),
        sa.Column("cabin", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("direct_only", sa.Boolean(), nullable=False),
        sa.Column("normalized_query", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "trip_type IN ('one_way', 'round_trip')", name=op.f("ck_search_queries_valid_trip_type")
        ),
        sa.CheckConstraint("adults >= 1", name=op.f("ck_search_queries_adults_positive")),
        sa.CheckConstraint("children >= 0", name=op.f("ck_search_queries_children_nonnegative")),
        sa.CheckConstraint("infants >= 0", name=op.f("ck_search_queries_infants_nonnegative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_queries")),
        sa.UniqueConstraint("query_hash", name=op.f("uq_search_queries_query_hash")),
    )
    op.create_index(
        "ix_search_queries_provider_updated",
        "search_queries",
        ["provider", "updated_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("normalized_email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('admin', 'member')", name=op.f("ck_users_valid_role")),
        sa.CheckConstraint(
            "status IN ('pending', 'active', 'disabled')", name=op.f("ck_users_valid_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("normalized_email", name=op.f("uq_users_normalized_email")),
    )
    op.create_table(
        "audit_events",
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=True),
        sa.Column("target_id", sa.String(length=80), nullable=True),
        sa.Column("request_id", sa.String(length=80), nullable=True),
        sa.Column("ip_hash", sa.String(length=128), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_events_actor_created",
        "audit_events",
        ["actor_user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "collection_runs",
        sa.Column("search_query_id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempt", sa.SmallInteger(), nullable=False),
        sa.Column("max_attempts", sa.SmallInteger(), nullable=False),
        sa.Column(
            "scheduled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_owner", sa.String(length=160), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("upstream_status", sa.String(length=80), nullable=True),
        sa.Column("schema_fingerprint", sa.String(length=128), nullable=True),
        sa.Column("itinerary_count", sa.Integer(), nullable=False),
        sa.Column("offer_count", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("run_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'leased', 'running', 'succeeded', 'failed', 'canceled')",
            name=op.f("ck_collection_runs_valid_status"),
        ),
        sa.CheckConstraint(
            "attempt >= 0 AND max_attempts >= 1", name=op.f("ck_collection_runs_valid_attempts")
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_collection_runs_provider_id_providers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["search_query_id"],
            ["search_queries.id"],
            name=op.f("fk_collection_runs_search_query_id_search_queries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collection_runs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_collection_runs_idempotency_key")),
    )
    op.create_index(
        "ix_collection_runs_query_scheduled",
        "collection_runs",
        ["search_query_id", "scheduled_at"],
        unique=False,
    )
    op.create_index(
        "ix_collection_runs_status_lease",
        "collection_runs",
        ["status", "lease_expires_at"],
        unique=False,
    )
    op.create_table(
        "daily_price_aggregates",
        sa.Column("search_query_id", sa.Uuid(), nullable=False),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("is_direct", sa.Boolean(), nullable=False),
        sa.Column("lowest_price_minor", sa.Integer(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("first_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lowest_price_minor >= 0", name=op.f("ck_daily_price_aggregates_price_nonnegative")
        ),
        sa.CheckConstraint(
            "sample_count > 0", name=op.f("ck_daily_price_aggregates_sample_count_positive")
        ),
        sa.ForeignKeyConstraint(
            ["search_query_id"],
            ["search_queries.id"],
            name=op.f("fk_daily_price_aggregates_search_query_id_search_queries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_price_aggregates")),
        sa.UniqueConstraint(
            "search_query_id",
            "service_date",
            "currency",
            "is_direct",
            name=op.f("uq_daily_price_aggregates_search_query_id_service_date_currency_is_direct"),
        ),
    )
    op.create_table(
        "invitations",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("normalized_email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("invited_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("accepted_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('admin', 'member')", name=op.f("ck_invitations_valid_role")),
        sa.ForeignKeyConstraint(
            ["accepted_by_user_id"],
            ["users.id"],
            name=op.f("fk_invitations_accepted_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
            name=op.f("fk_invitations_invited_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_invitations_token_hash")),
    )
    op.create_index(
        "ix_invitations_email_pending",
        "invitations",
        ["normalized_email", "accepted_at", "revoked_at"],
        unique=False,
    )
    op.create_table(
        "notification_channels",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("channel_type", sa.String(length=24), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("secret_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("config_redacted", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "channel_type IN ('email', 'telegram', 'bark', 'pushplus', 'webhook')",
            name=op.f("ck_notification_channels_valid_channel_type"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_channels_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_channels")),
        sa.UniqueConstraint("user_id", "name", name=op.f("uq_notification_channels_user_id_name")),
    )
    op.create_index(
        "ix_notification_channels_user_enabled",
        "notification_channels",
        ["user_id", "enabled"],
        unique=False,
    )
    op.create_table(
        "search_legs",
        sa.Column("search_query_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("origin_code", sa.String(length=8), nullable=False),
        sa.Column("destination_code", sa.String(length=8), nullable=False),
        sa.Column("departure_date", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "origin_code <> destination_code", name=op.f("ck_search_legs_different_airports")
        ),
        sa.CheckConstraint("position >= 0", name=op.f("ck_search_legs_position_nonnegative")),
        sa.ForeignKeyConstraint(
            ["search_query_id"],
            ["search_queries.id"],
            name=op.f("fk_search_legs_search_query_id_search_queries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_legs")),
        sa.UniqueConstraint(
            "search_query_id", "position", name=op.f("uq_search_legs_search_query_id_position")
        ),
    )
    op.create_index(
        "ix_search_legs_route_date",
        "search_legs",
        ["origin_code", "destination_code", "departure_date"],
        unique=False,
    )
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_hash", sa.String(length=128), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    op.create_index(
        "ix_sessions_user_active", "sessions", ["user_id", "expires_at", "revoked_at"], unique=False
    )
    op.create_table(
        "subscriptions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("search_query_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("poll_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("next_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "poll_interval_seconds >= 300", name=op.f("ck_subscriptions_poll_interval_minimum")
        ),
        sa.ForeignKeyConstraint(
            ["search_query_id"],
            ["search_queries.id"],
            name=op.f("fk_subscriptions_search_query_id_search_queries"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_subscriptions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
    )
    op.create_index(
        "ix_subscriptions_due", "subscriptions", ["enabled", "next_due_at"], unique=False
    )
    op.create_index(
        "ix_subscriptions_user_enabled", "subscriptions", ["user_id", "enabled"], unique=False
    )
    op.create_table(
        "alert_rules",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("rule_type", sa.String(length=40), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("threshold_price_minor", sa.Integer(), nullable=True),
        sa.Column("threshold_currency", sa.String(length=3), nullable=True),
        sa.Column("threshold_percentage", sa.SmallInteger(), nullable=True),
        sa.Column("comparison_window_days", sa.SmallInteger(), nullable=True),
        sa.Column("cooldown_seconds", sa.Integer(), nullable=False),
        sa.Column("quiet_hours_start", sa.Time(), nullable=True),
        sa.Column("quiet_hours_end", sa.Time(), nullable=True),
        sa.Column("quiet_hours_timezone", sa.String(length=64), nullable=True),
        sa.Column("rule_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rule_type IN ('price_threshold', 'absolute_drop', 'percentage_drop', "
            "'new_low', 'direct_available', 'matching_itinerary', 'round_trip_range', "
            "'data_stale', 'schema_drift')",
            name=op.f("ck_alert_rules_valid_rule_type"),
        ),
        sa.CheckConstraint(
            "cooldown_seconds >= 0", name=op.f("ck_alert_rules_cooldown_nonnegative")
        ),
        sa.CheckConstraint(
            "threshold_percentage IS NULL OR "
            "(threshold_percentage > 0 AND threshold_percentage <= 10000)",
            name=op.f("ck_alert_rules_percentage_basis_points"),
        ),
        sa.CheckConstraint(
            "threshold_price_minor IS NULL OR threshold_price_minor >= 0",
            name=op.f("ck_alert_rules_price_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_alert_rules_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_alert_rules_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_rules")),
    )
    op.create_index(
        "ix_alert_rules_subscription_enabled",
        "alert_rules",
        ["subscription_id", "enabled"],
        unique=False,
    )
    op.create_index(
        "ix_alert_rules_user_enabled", "alert_rules", ["user_id", "enabled"], unique=False
    )
    op.create_table(
        "collection_artifacts",
        sa.Column("collection_run_id", sa.Uuid(), nullable=False),
        sa.Column("artifact_type", sa.String(length=60), nullable=False),
        sa.Column("storage_uri", sa.Text(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("content_encoding", sa.String(length=40), nullable=True),
        sa.Column("redaction_version", sa.String(length=40), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "size_bytes >= 0", name=op.f("ck_collection_artifacts_size_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["collection_run_id"],
            ["collection_runs.id"],
            name=op.f("fk_collection_artifacts_collection_run_id_collection_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collection_artifacts")),
        sa.UniqueConstraint(
            "collection_run_id",
            "artifact_type",
            "checksum_sha256",
            name=op.f("uq_collection_artifacts_collection_run_id_artifact_type_checksum_sha256"),
        ),
    )
    op.create_table(
        "itineraries",
        sa.Column("collection_run_id", sa.Uuid(), nullable=False),
        sa.Column("search_query_id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("provider_itinerary_id", sa.String(length=240), nullable=True),
        sa.Column("fingerprint", sa.String(length=128), nullable=False),
        sa.Column("total_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("stop_count", sa.SmallInteger(), nullable=False),
        sa.Column("is_direct", sa.Boolean(), nullable=False),
        sa.Column("leg_count", sa.SmallInteger(), nullable=False),
        sa.Column("itinerary_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("stop_count >= 0", name=op.f("ck_itineraries_stops_nonnegative")),
        sa.CheckConstraint(
            "total_duration_minutes > 0", name=op.f("ck_itineraries_duration_positive")
        ),
        sa.ForeignKeyConstraint(
            ["collection_run_id"],
            ["collection_runs.id"],
            name=op.f("fk_itineraries_collection_run_id_collection_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_itineraries_provider_id_providers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["search_query_id"],
            ["search_queries.id"],
            name=op.f("fk_itineraries_search_query_id_search_queries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_itineraries")),
        sa.UniqueConstraint(
            "collection_run_id",
            "fingerprint",
            name=op.f("uq_itineraries_collection_run_id_fingerprint"),
        ),
    )
    op.create_index(
        "ix_itineraries_query_created",
        "itineraries",
        ["search_query_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "schema_observations",
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("collection_run_id", sa.Uuid(), nullable=True),
        sa.Column("endpoint", sa.String(length=160), nullable=False),
        sa.Column("schema_fingerprint", sa.String(length=128), nullable=False),
        sa.Column("field_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["collection_run_id"],
            ["collection_runs.id"],
            name=op.f("fk_schema_observations_collection_run_id_collection_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_schema_observations_provider_id_providers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schema_observations")),
        sa.UniqueConstraint(
            "provider_id",
            "endpoint",
            "schema_fingerprint",
            name=op.f("uq_schema_observations_provider_id_endpoint_schema_fingerprint"),
        ),
    )
    op.create_index(
        "ix_schema_observations_provider_created",
        "schema_observations",
        ["provider_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "subscription_filters",
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("airline_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("origin_airport_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "destination_airport_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("max_price_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("max_stops", sa.SmallInteger(), nullable=True),
        sa.Column("max_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("departure_time_start_minutes", sa.SmallInteger(), nullable=True),
        sa.Column("departure_time_end_minutes", sa.SmallInteger(), nullable=True),
        sa.Column("additional_filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "max_duration_minutes IS NULL OR max_duration_minutes > 0",
            name=op.f("ck_subscription_filters_duration_positive"),
        ),
        sa.CheckConstraint(
            "max_price_minor IS NULL OR max_price_minor >= 0",
            name=op.f("ck_subscription_filters_price_nonnegative"),
        ),
        sa.CheckConstraint(
            "max_stops IS NULL OR max_stops >= 0",
            name=op.f("ck_subscription_filters_stops_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_subscription_filters_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_filters")),
        sa.UniqueConstraint(
            "subscription_id", name=op.f("uq_subscription_filters_subscription_id")
        ),
    )
    op.create_table(
        "alert_events",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("alert_rule_id", sa.Uuid(), nullable=False),
        sa.Column("collection_run_id", sa.Uuid(), nullable=True),
        sa.Column("deduplication_key", sa.String(length=180), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("event_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("suppressed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suppression_reason", sa.String(length=160), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["alert_rule_id"],
            ["alert_rules.id"],
            name=op.f("fk_alert_events_alert_rule_id_alert_rules"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["collection_run_id"],
            ["collection_runs.id"],
            name=op.f("fk_alert_events_collection_run_id_collection_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_alert_events_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_events")),
        sa.UniqueConstraint("deduplication_key", name=op.f("uq_alert_events_deduplication_key")),
    )
    op.create_index(
        "ix_alert_events_rule_created",
        "alert_events",
        ["alert_rule_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_alert_events_user_created", "alert_events", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "alert_rule_channels",
        sa.Column("alert_rule_id", sa.Uuid(), nullable=False),
        sa.Column("notification_channel_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_rule_id"],
            ["alert_rules.id"],
            name=op.f("fk_alert_rule_channels_alert_rule_id_alert_rules"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["notification_channel_id"],
            ["notification_channels.id"],
            name=op.f("fk_alert_rule_channels_notification_channel_id_notification_channels"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_rule_channels")),
        sa.UniqueConstraint(
            "alert_rule_id",
            "notification_channel_id",
            name=op.f("uq_alert_rule_channels_alert_rule_id_notification_channel_id"),
        ),
    )
    op.create_table(
        "fare_offers",
        sa.Column("collection_run_id", sa.Uuid(), nullable=False),
        sa.Column("itinerary_id", sa.Uuid(), nullable=False),
        sa.Column("provider_offer_id", sa.String(length=240), nullable=True),
        sa.Column("fingerprint", sa.String(length=128), nullable=False),
        sa.Column("cabin", sa.String(length=32), nullable=False),
        sa.Column("fare_family", sa.String(length=120), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("total_price_minor", sa.Integer(), nullable=False),
        sa.Column("base_price_minor", sa.Integer(), nullable=True),
        sa.Column("tax_minor", sa.Integer(), nullable=True),
        sa.Column("seats_remaining", sa.SmallInteger(), nullable=True),
        sa.Column("baggage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("refund_change_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("offer_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "base_price_minor IS NULL OR base_price_minor >= 0",
            name=op.f("ck_fare_offers_base_price_nonnegative"),
        ),
        sa.CheckConstraint(
            "tax_minor IS NULL OR tax_minor >= 0", name=op.f("ck_fare_offers_tax_nonnegative")
        ),
        sa.CheckConstraint(
            "total_price_minor >= 0", name=op.f("ck_fare_offers_total_price_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["collection_run_id"],
            ["collection_runs.id"],
            name=op.f("fk_fare_offers_collection_run_id_collection_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["itinerary_id"],
            ["itineraries.id"],
            name=op.f("fk_fare_offers_itinerary_id_itineraries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fare_offers")),
        sa.UniqueConstraint(
            "collection_run_id",
            "itinerary_id",
            "fingerprint",
            name=op.f("uq_fare_offers_collection_run_id_itinerary_id_fingerprint"),
        ),
    )
    op.create_index(
        "ix_fare_offers_itinerary_price",
        "fare_offers",
        ["itinerary_id", "total_price_minor"],
        unique=False,
    )
    op.create_table(
        "segments",
        sa.Column("itinerary_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("leg_position", sa.SmallInteger(), nullable=False),
        sa.Column("marketing_airline_code", sa.String(length=8), nullable=False),
        sa.Column("operating_airline_code", sa.String(length=8), nullable=True),
        sa.Column("flight_number", sa.String(length=16), nullable=False),
        sa.Column("origin_airport_code", sa.String(length=8), nullable=False),
        sa.Column("destination_airport_code", sa.String(length=8), nullable=False),
        sa.Column("departure_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("arrival_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("departure_local", sa.DateTime(), nullable=False),
        sa.Column("arrival_local", sa.DateTime(), nullable=False),
        sa.Column("departure_timezone", sa.String(length=64), nullable=False),
        sa.Column("arrival_timezone", sa.String(length=64), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("aircraft_code", sa.String(length=24), nullable=True),
        sa.Column("segment_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("duration_minutes > 0", name=op.f("ck_segments_duration_positive")),
        sa.CheckConstraint(
            "position >= 0 AND leg_position >= 0", name=op.f("ck_segments_positions_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["itinerary_id"],
            ["itineraries.id"],
            name=op.f("fk_segments_itinerary_id_itineraries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_segments")),
        sa.UniqueConstraint(
            "itinerary_id", "position", name=op.f("uq_segments_itinerary_id_position")
        ),
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("alert_event_id", sa.Uuid(), nullable=False),
        sa.Column("notification_channel_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempt_count", sa.SmallInteger(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_message_id", sa.String(length=180), nullable=True),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("response_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'sending', 'succeeded', 'failed', 'suppressed')",
            name=op.f("ck_notification_deliveries_valid_status"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_notification_deliveries_attempts_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["alert_event_id"],
            ["alert_events.id"],
            name=op.f("fk_notification_deliveries_alert_event_id_alert_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["notification_channel_id"],
            ["notification_channels.id"],
            name=op.f("fk_notification_deliveries_notification_channel_id_notification_channels"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_deliveries")),
        sa.UniqueConstraint(
            "alert_event_id",
            "notification_channel_id",
            name=op.f("uq_notification_deliveries_alert_event_id_notification_channel_id"),
        ),
    )
    op.create_index(
        "ix_notification_deliveries_due",
        "notification_deliveries",
        ["status", "next_attempt_at"],
        unique=False,
    )
    op.create_table(
        "price_observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("search_query_id", sa.Uuid(), nullable=False),
        sa.Column("collection_run_id", sa.Uuid(), nullable=False),
        sa.Column("itinerary_id", sa.Uuid(), nullable=False),
        sa.Column("fare_offer_id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("offer_fingerprint", sa.String(length=128), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("total_price_minor", sa.Integer(), nullable=False),
        sa.Column("is_lowest", sa.Boolean(), nullable=False),
        sa.Column("is_direct", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "total_price_minor >= 0", name=op.f("ck_price_observations_price_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["collection_run_id"],
            ["collection_runs.id"],
            name=op.f("fk_price_observations_collection_run_id_collection_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["fare_offer_id"],
            ["fare_offers.id"],
            name=op.f("fk_price_observations_fare_offer_id_fare_offers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["itinerary_id"],
            ["itineraries.id"],
            name=op.f("fk_price_observations_itinerary_id_itineraries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_price_observations_provider_id_providers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["search_query_id"],
            ["search_queries.id"],
            name=op.f("fk_price_observations_search_query_id_search_queries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", "observed_at", name=op.f("pk_price_observations")),
        sa.UniqueConstraint(
            "observed_at",
            "collection_run_id",
            "offer_fingerprint",
            name=op.f("uq_price_observations_observed_at_collection_run_id_offer_fingerprint"),
        ),
        postgresql_partition_by="RANGE (observed_at)",
    )
    op.create_index(
        "ix_price_observations_search_observed",
        "price_observations",
        ["search_query_id", "observed_at"],
        unique=False,
    )
    _create_price_partitions()
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_price_observations_search_observed", table_name="price_observations")
    op.drop_table("price_observations")
    op.drop_index("ix_notification_deliveries_due", table_name="notification_deliveries")
    op.drop_table("notification_deliveries")
    op.drop_table("segments")
    op.drop_index("ix_fare_offers_itinerary_price", table_name="fare_offers")
    op.drop_table("fare_offers")
    op.drop_table("alert_rule_channels")
    op.drop_index("ix_alert_events_user_created", table_name="alert_events")
    op.drop_index("ix_alert_events_rule_created", table_name="alert_events")
    op.drop_table("alert_events")
    op.drop_table("subscription_filters")
    op.drop_index("ix_schema_observations_provider_created", table_name="schema_observations")
    op.drop_table("schema_observations")
    op.drop_index("ix_itineraries_query_created", table_name="itineraries")
    op.drop_table("itineraries")
    op.drop_table("collection_artifacts")
    op.drop_index("ix_alert_rules_user_enabled", table_name="alert_rules")
    op.drop_index("ix_alert_rules_subscription_enabled", table_name="alert_rules")
    op.drop_table("alert_rules")
    op.drop_index("ix_subscriptions_user_enabled", table_name="subscriptions")
    op.drop_index("ix_subscriptions_due", table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index("ix_sessions_user_active", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("ix_search_legs_route_date", table_name="search_legs")
    op.drop_table("search_legs")
    op.drop_index("ix_notification_channels_user_enabled", table_name="notification_channels")
    op.drop_table("notification_channels")
    op.drop_index("ix_invitations_email_pending", table_name="invitations")
    op.drop_table("invitations")
    op.drop_table("daily_price_aggregates")
    op.drop_index("ix_collection_runs_status_lease", table_name="collection_runs")
    op.drop_index("ix_collection_runs_query_scheduled", table_name="collection_runs")
    op.drop_table("collection_runs")
    op.drop_index("ix_audit_events_actor_created", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("users")
    op.drop_index("ix_search_queries_provider_updated", table_name="search_queries")
    op.drop_table("search_queries")
    op.drop_table("providers")
    # ### end Alembic commands ###
